services:
  db:
    image: postgres:15
    container_name: bulimova-postgres
    environment:
      POSTGRES_DB: bulimova_db
      POSTGRES_USER: bulimova
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bulimova-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bulimova_db
      SPRING_DATASOURCE_USERNAME: bulimova
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
